name: dart_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  native_toolchain_rust: ^0.1.0-dev.7
  native_assets_cli: ^0.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
